name: Build and Publish with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Get Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    - name: Build
      run: |
        npm ci
        RUNTIME=prod \
          APP_API_ENDPOINT=${{ secrets.APP_API_ENDPOINT }} \
          npm run build:www

    - name: Publish
      run: |
        cd ./dist
        tar -czvf cmx-battleship-dist.tar.gz ./cmx-battleship
        export ASSET_SHA256=$(sha256sum cmx-battleship-dist.tar.gz | awk '{print $1;}')
        aws codeartifact publish-package-version \
          --domain morriswa-org --repository morriswa-central \
          --format generic --namespace org.morriswa --package cmx-battleship-dist \
          --package-version ${{ steps.package-version.outputs.current-version}} \
          --asset-content cmx-battleship-dist.tar.gz \
          --asset-name cmx-battleship-dist.tar.gz \
          --asset-sha256 "$ASSET_SHA256" --unfinished
